// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CategoryForImport { id: number, name: string, description: string, num_records: number, created: Date, updated: Date, user: string, }