// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TimeRecordForImport { id: number, project: number, start_time: Date, stop_time: Date, total_seconds: bigint, approved: boolean, }